"""Copy profile data from the legacy application to the profiles application."""

# Generated by Django 6.1 on 2026-08-14 11:43

from django.db import migrations


BATCH_SIZE = 1000


def copy_data(apps, schema_editor):
    """
    Copy profiles from the legacy application.

    The data is copied from the historical Profile model of the
    ``oc_lettings_site`` application to the new ``profiles`` model.
    Records are processed in batches to limit memory consumption when
    migrating a large dataset.

    ``iterator()`` is used to retrieve records progressively from the
    database instead of loading the entire queryset into memory.
    ``bulk_create()`` is used for each batch to reduce the number of
    database queries.

    Args:
        apps: Django application registry providing access to the
            historical versions of the models.
        schema_editor: Database schema editor provided by Django during
            the migration. It is not used directly by this migration.
    """
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    profiles = []

    for old_profile in OldProfile.objects.iterator(chunk_size=BATCH_SIZE):
        profiles.append(
            NewProfile(
                id=old_profile.id,
                user_id=old_profile.user_id,
                favorite_city=old_profile.favorite_city,
            )
        )

        if len(profiles) >= BATCH_SIZE:
            NewProfile.objects.bulk_create(profiles)
            profiles = []

    if profiles:
        NewProfile.objects.bulk_create(profiles)


class Migration(migrations.Migration):
    """Define the migration that copies legacy data to the new models."""

    dependencies = [
        ("profiles", "0001_initial"),
        (
            "oc_lettings_site",
            "0002_alter_address_id_alter_letting_id_alter_profile_id_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
