# Generated by Django 6.1 on 2026-08-14 11:43

from django.db import migrations

BATCH_SIZE = 1000

def copy_data(apps, schema_editor):
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    OldLetting = apps.get_model("oc_lettings_site", "Letting")

    NewAddress = apps.get_model("lettings", "Address")
    NewLetting = apps.get_model("lettings", "Letting")

    addresses = []

    for old_address in OldAddress.objects.iterator(chunk_size=BATCH_SIZE):
        addresses.append(
            NewAddress(
                id=old_address.id,
                number=old_address.number,
                street=old_address.street,
                city=old_address.city,
                state=old_address.state,
                zip_code=old_address.zip_code,
                country_iso_code=old_address.country_iso_code,
            )
        )

        if len(addresses) >= BATCH_SIZE:
            NewAddress.objects.bulk_create(addresses)
            addresses = []

    if addresses:
        NewAddress.objects.bulk_create(addresses)

    lettings = []
    for old_letting in OldLetting.objects.iterator(chunk_size=BATCH_SIZE):
        lettings.append(
            NewLetting(
                id=old_letting.id,
                title=old_letting.title,
                address_id=old_letting.address_id,
            )
        )
        if len(lettings) >= BATCH_SIZE:
            NewLetting.objects.bulk_create(lettings)
            lettings = []
            
    if lettings:
        NewLetting.objects.bulk_create(lettings)


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "0002_alter_address_id_alter_letting_id_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]