# Generated by Django 6.1 on 2026-08-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "oc_lettings_site",
            "0002_alter_address_id_alter_letting_id_alter_profile_id_and_more",
        ),
        ("lettings", "0002_copy_data"),
        ("profiles", "0002_copy_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
